### ISSUE TITLE
tests do not run properly in obs

### ISSUE THREAD

**Issue by tampakrap** [smithfarm/dochazka-rest#113]
```
[   89s] t/dispatch/001-resource.t ...... skipped: DOCHAZKA_MASON_INIT_FAIL ARGS: ['OUCH!!! DOCHAZKA_STATE_DIR /var/lib/dochazka-rest is not readable by me! at /home/abuild/rpmbuild/BUILD/App-Dochazka-REST-0.542/blib/lib/App/Dochazka/REST.pm line 250.
```

see https://build.opensuse.org/build/home:smithfarm:branches:Application:Dochazka:staging/SLE_12_SP1/x86_64/perl-App-Dochazka-REST/_log

**Comment by smithfarm** [comment]
The relevant code in question:

```
    plan skip_all => $status->text unless $status->ok;
    plan skip_all => 'Integration testing environment not detected - skipping' unless $status->ok;

    note( "Check status of database server connection" );
    plan skip_all => "PostgreSQL server is unreachable" unless conn_up();
```

Even if we did make DOCHAZKA_STATE_DIR point to a temporary directory created by the test, all that would happen is the test would proceed to the next line: "Check status of database server connection". Since there will never be a PostgreSQL server reachable inside in the OBS build environment, the test will get skipped anyway.
