### ISSUE TITLE
Maintain the spec file in git

### ISSUE THREAD

**Issue by smithfarm** [smithfarm/dochazka-rest#80]
Bring the spec file and cpanspec.yml file into git and maintain them there. Use "extract-file" source service to extract them from the tarball.

**Comment by tampakrap** [comment]
I dislike this approach for three reasons:
* personal taste (not a good argument I know)
* it is not common
* it will not update the changelog. This is important though for factory and leap submissions, and since we are still need to update it manually, I don't really see the benefit of automatic the tarball update since the whole procedure is not fully automated

Opinions?

**Comment by smithfarm** [comment]
The advantage of this approach is that it *guarantees* the spec file will always be maintained only in one place.

**Comment by smithfarm** [comment]
However, since @tampakrap has agreed to maintain the OBS/IBS packages and since the spec file is automatically generated, it's not so important to have the spec file in git. Closing.
